### ISSUE TITLE
Add Travis CI release build

### ISSUE THREAD

**Issue by jbadeau** [projectit-org/ProjectIt#13]
Create a job for releasing all modules.

**Comment by jbadeau** [comment]
Was busy this week with a new job. Gonna set up the release build this weekend.

**Comment by joswarmer** [comment]
Great!

**Comment by jbadeau** [comment]
There seems to be an issue with the build. Can’t create the release.

It worked locally but only for the demo wuxh shouldn’t be released

**Comment by jbadeau** [comment]
You need to register the master with Travis. I can’t do it as I’m not the owner of the master branch

**Comment by jbadeau** [comment]
Takes 3 minutes

**Comment by joswarmer** [comment]
Working on it, tTrying to find out how to register a branch with Travis ....

**Comment by joswarmer** [comment]
Can't find anywhere the option to register a branch with Travis. The master branch is being built by Travis, so that's ok. Could it have something to do with the fact that the master branch is protected in Github?

**Comment by jbadeau** [comment]
I guess this can be closed

**Comment by joswarmer** [comment]
Indeed
