### ISSUE TITLE
File styles.scss is missing in distribution

### ISSUE THREAD

**Issue by joswarmer** [projectit-org/ProjectIt#26]
When trying to use the first release, it seems that the file `styles.scss` is missing.
It should be in `@projectit/core/dist/components/dropdopwn`.

**Comment by joswarmer** [comment]
All scss files and the fonts are missing.

**Comment by jbadeau** [comment]
Will have a look tomorrow

**Comment by joswarmer** [comment]
I think IO fixed it, it seems that the typescript compiler ignores non .ts or .js files,  and does not copy them to the output directory. You need to do that yourself in the build script.

**Comment by joswarmer** [comment]
Also found that the package.json from all packages is incomplete. While developing they use the package.json at the root of the project,  but these dependencies are not copied to the individual packages.  When using ProjectIt in a standalone project I get many errors because of this.

**Comment by joswarmer** [comment]
Fixed build scripts to copy .scss and font files to distribution folder. The ProjectIt example project at https://github.com/projectit-org/ProjectIt-example now correctly runs.
