### ISSUE TITLE
Enable all typescript build time checks

### ISSUE THREAD

**Issue by jbadeau** [projectit-org/ProjectIt#5]
To get the most out of the tsc then all ts build time check should be enabled:

 "noFallthroughCasesInSwitch": true,
"noImplicitAny": true,
"noImplicitReturns": true,
"skipLibCheck": true,
"strictNullChecks": true,
"strint": true

**Comment by jbadeau** [comment]
There are allot of issue here. We really need to fix them as the< cause issues with standard build settings

**Comment by joswarmer** [comment]
Fixed a batch of these

**Comment by jbadeau** [comment]
Cool :)

**Comment by joswarmer** [comment]
Will not do, as the checks are too strict
